events {}
stream {
    upstream kv_backend {
        server node1:8081;
        server node2:8082;
        server node3:8083;
    }

    server {
        listen 8080;
        proxy_pass kv_backend;
    }
}
